### ISSUE TITLE
Autocomplete only appearing for iOS

### ISSUE THREAD

**Issue by joshbedo** [FaridSafi/react-native-google-places-autocomplete#144]
Right now we're using the autocomplete in an Exponent project and it appear fine in iOS but the autocomplete doesn't show in Android. Is there some kind of additional setup for Android? Thanks!

**Comment by mmatheusmmiguel** [comment]
I would also like to know.

**Comment by RxAssim** [comment]
@joshbedo Did you find a fix for this ?

**Comment by gitlovenotwar** [comment]
I'm having the same problem. This is not working on android

**Comment by kamranmasood** [comment]
anyone solved this, I am also stuck in the same situation.

**Comment by lorenzopicoli** [comment]
Are you placing the component inside the header? I had this problem because on android the component cannot draw outside it's parent (https://github.com/facebook/react-native/issues/3198). So in my case, the search bar was in the header and it worked on iOS, but the result list was clipped on Android
