### ISSUE TITLE
`styles` is not a supported property of `View`, did you mean `style` (singular)?

### ISSUE THREAD

**Issue by gibson** [FaridSafi/react-native-google-places-autocomplete#220]
On react native 0.49 i have a error ``styles` is not a supported property of `View`, did you mean `style` (singular)?` if component has props `styles` or try use it

**Comment by danReynolds** [comment]
I'm also getting this

**Comment by willdeuschle** [comment]
The problem is in `GooglePlacesAutocomplete.js` line 662. They're spreading `this.props`, which includes a prop named `styles`. This is getting passed on to the FlatList, which eventually dumps it on the View, and it seems that newer versions of react-native catch this. I changed all references to `styles` to be `extraStyles`, which fixes the problem.

**Comment by freddiewanah** [comment]
update please

**Comment by kristinadarroch** [comment]
for me, i accidentally put 'styles' on the element instead of 'style'. Once I changed it from styles to style the error was resolved.

**Comment by guilhermepontes** [comment]
Thanks for informing. I
