### ISSUE TITLE
Custom rendered row causing an error on press

### ISSUE THREAD

**Issue by kaykdm** [FaridSafi/react-native-google-places-autocomplete#249]
Hi guys, 
So when I press my custom rendered row, I get an error saying `Warning: Failed prop type: Invalid prop 'value' of type 'object' supplied to 'TextInput', expected 'string'.`

and this is how I am rendering custom row:  
```
<GooglePlacesAutocomplete
       placeholder='Enter Location'
       minLength={2}
       returnKeyType={'default'}
       listViewDisplayed='true'
       autoFocus={true}
       fetchDetails={true}
       inputRef={el => this.inputElement = el}
       text={this.props.value}
       renderDescription={row => {
         return (
           row.description ?
             <Text>
               <Icon style={{marginTop: 50}} name="place" size={25} color="black" />
               {row.description}
             </Text>
           : row.vicinity
         )
       }}
       onPress={(this.selectLocItem)}
       query={{
         key: 'api key',
         language: 'en', // language of the results
         types: 'geocode' // default: 'geocode'
       }}
       styles={locationInputStyles}
       debounce={200}
       currentLocation={true}
       enablePoweredByContainer={false}
 />
```
I did some digging and I found that if I use `renderDescription={row => row.description || row.vicinity}`, I will not get any error. However, I want to use my custom row for the list. 

How can I fix this?

**Comment by TimothyDLewis** [comment]
Looking at the code for `GooglePlacesAutocomplete.js`, you can see that the `_onPress()` function calls:
```
this.setState({
    text: this._renderDescription( rowData ),
});
```
Looking at `_renderDescription()` we can see that it in turn calls:
```
if (this.props.renderDescription) {
    return this.props.renderDescription(rowData);
}
```
Lastly, the value passed to the `<TextInput>` component is `value={this.state.text}`. 

Since you've supplied a custom function for `renderDescription()` that returns a `React` component, you're getting this error (as `this.state.text` is being set to as your `<Text>` component). 

If you update your code from `renderDescription(...)` to `renderRow(...)`, it _should_ work (there's a few styling issues in my case, but the error is gone).

**Comment by kaykdm** [comment]
@TimothyDLewis thank you so much. it worked!!!
