### ISSUE TITLE
Example doesn't return any results.

### ISSUE THREAD

**Issue by DheenodaraRao** [FaridSafi/react-native-google-places-autocomplete#256]
I am a beginner and I want to add the autocomplete in my react native app. Hence I tried to run the example shown by your page and I have edited the API key as well. There is no results shown. I have seen the GooglePlacesAutocomplete.js file and I am not sure which function to use in order to get the search results.

Please give some hits.

**Comment by ahmadvaroqua** [comment]
@DheenodaraRao I had a similar issue with the example. If you are seeing "empty" rows (like I did) after entering the current location, it's probably because you don't have a row style defined. Try commenting out the custom renderDescription property like so:

`// renderDescription={row => row.description}`

**Comment by DheenodaraRao** [comment]
@ahmadvaroqua Thanks. I will try it.
