### ISSUE TITLE
GooglePlacesSearchQuery vs. query

### ISSUE THREAD

**Issue by BrentGrammer** [FaridSafi/react-native-google-places-autocomplete#373]
Thanks for the package and work on this.  I'm a little confused as to how to use this with my project so wanted to ask for help here.

Can someone explain to me the difference between query and GooglePlacesSearchQuery and how to use them? I've been trying to get search results limited by type to 'bar' and nothing seems to be working.  What is the difference between the type prop in query and the type (or types?) prop in GooglePlacesSearchQuery?  I've been trying to find explanations and have had no luck.  

I want to get a list of places not only if the user searches by address or business name, but by keyword, i.e. if they put 'bar' into the search input.  Currently I do not get a relevant list of results from entering the word 'bar' or 'bar near `city name`'.  The results seem unrelated and include places that are temples among other things, and not bars.  Can anyone point me in the right direction?

**Comment by SkyRune** [comment]
Yep same problem here I have this :

                           ```
 nearbyPlacesAPI='GooglePlacesSearch' 
                            GooglePlacesSearchQuery={{
                                rankby: 'distance',
                                types: 'bar',
                            }}
```
But still, the result are not restricted to bars only.

**Comment by dillonfromdallas** [comment]
@FaridSafi - Could we get some insight on this?

In my current project, I'm looking to allow user input for placetypes, as well as business names.

(I.e. Ideally, a user can enter "cafe", "coffee", or "Starbucks", and the AutoComplete will return a list of relevant options.)

**Comment by Lelelo1** [comment]
CurrentLocation and  predefinedPlacesAlwaysVisible props has to be true. Pressing the CurrentLocation shows the results

**Comment by bell-steven** [comment]
> Can someone explain to me the difference between query and GooglePlacesSearchQuery and how to use them? 

The `GooglePlacesSearchQuery` is used when `currentLocation={true}` and `nearbyPlacesAPI='GooglePlacesSearch'`.  
In that case, we are calling a different API, so the query is a little different. See the Google [docs](https://developers.google.com/places/web-service/search#PlaceSearchRequests) for more details and options. 

The `query` prop is used for regular text search.  See the Google doc [here](https://developers.google.com/places/web-service/autocomplete#place_autocomplete_requests) for more on that. 

There is `query`, `GooglePlacesDetailsQuery`, `GooglePlacesSearchQuery`, and `GoogleReverseGeocodingQuery`.  More on how it all works below.

> Currently I do not get a relevant list of results from entering the word 'bar' or 'bar near city name'.

This is not possible right now with the library.  This might be added in the next major version. 
The Google Places Query Autocomplete [API](https://developers.google.com/places/web-service/query#query_autocomplete_requests) would cover this.

##
This is pretty confusing, and we need proper docs for this. 
Here is the breakdown of the Google APIs and how they are used in the library, to the best of my understanding.


Google Provides a bunch of web APIs for finding an address or place, and getting it’s details.
There are the Google Places Web APIs ([Place Search](https://developers.google.com/places/web-service/search), [Place Details](https://developers.google.com/places/web-service/details), [Place Photos](https://developers.google.com/places/web-service/photos), [Place Autocomplete](https://developers.google.com/places/web-service/autocomplete), [Query Autocomplete](https://developers.google.com/places/web-service/query)) and the [Google Geocode API](https://developers.google.com/maps/documentation/geocoding/intro) .

The are 5 Google Places APIs:
 - **Place Autocomplete -** automatically fills in the name and/or address of a place as users type.
 - **Place Details -** returns more detailed information about a specific place (using a place_id that you get from Place Search, Place Autocomplete, or Query Autocomplete). 
 - **Place Photos -** provides access to the millions of place-related photos stored in Google's Place database (using a reference_id that you get from Place Search, Place Autocomplete, or Query Autocomplete).
 - **Place Search -** returns a list of places based on a user's location or search string.
- **Query Autocomplete -** provides a query prediction service for text-based geographic searches, returning suggested queries as users type.

The **Geocoding API** allows you to convert an address into geographic coordinates (lat, long) and to "reverse geocode",  which is the process of converting geographic coordinates into a human-readable address.

### Which APIs does this library use?

Place Autocomplete API, Place Details API, Place Search API and the Geocoding API.

We use the **Place Autocomplete API** to get suggestions as you type.  When you click on a suggestion, we use the **Place Details API** to get more information about the place. 

We use the **Geocoding API** and the **Place Search API** to use your current location to get results.

Because the query parameters are different for each API, there are 4 different "query" props.

1) Autocomplete -> `query` ([options](https://developers.google.com/places/web-service/autocomplete#place_autocomplete_requests))
2) Place Details -> `GooglePlacesDetailsQuery` ([options](https://developers.google.com/places/web-service/details#PlaceDetailsRequests))
3) Nearby Search -> `GooglePlacesSearchQuery` ([options](https://developers.google.com/places/web-service/search#PlaceSearchRequests))
4) Geocode -> `GoogleReverseGeocodingQuery` ([options](https://developers.google.com/maps/documentation/geocoding/intro#GeocodingRequests))

Number 1 is used while getting autocomplete results.
Number 2 is used when you click on a result. 
Number 3 is used when you select 'Current Location' to load nearby results.
Number 4 is used when `nearbyPlacesAPI='GoogleReverseGeocoding'` is set and you select 'Current Location' to load nearby results.
