### ISSUE TITLE
Special characters break the request. 

### ISSUE THREAD

**Issue by sambwest** [FaridSafi/react-native-google-places-autocomplete#42]
Hi,

It appears that if you use a hash # in your query then it breaks the input. 

Why would I want a hash in the lookup? In Colombia the addresses are in the following format: Calle 11 #220-25. The hash is needed to look up the address. 

Quick look at the code and you appear to be using encodeURI() to encode special chars before submitting. This function encodes special characters, except: , / ? : @ & = + $ #. There is an alternative encodeURIComponent() which also encodes those ones. 

Happy to to submit a PR if you like otherwise a quick swap out should sort it.

Thanks for your hard work,

Sam

**Comment by myaskevich** [comment]
Hi Sam,
Thanks for the investigation and insights!
Of course I'll gladly merge it!

Sincerely,
Maxim Yaskevich




On Thu, Aug 4, 2016 at 12:46 AM +0200, "Sam West" <notifications@github.com> wrote:












Hi,



It appears that if you use a hash # in your query then it breaks the input. 



Why would I want a hash in the lookup? In Colombia the addresses are in the following format: Calle 11 #220-25. The hash is needed to look up the address. 



Quick look at the code and you appear to be using encodeURI() to encode special chars before submitting. This function encodes special characters, except: , / ? : @ & = + $ #. There is an alternative encodeURIComponent() which also encodes those ones. 



Happy to to submit a PR if you like otherwise a quick swap out should sort it.



Thanks for your hard work,



Sam

**Comment by myaskevich** [comment]
Thanks, @sambwest !
Now available in v1.2.1
