### ISSUE TITLE
Questions: How to get streets for specified city only

### ISSUE THREAD

**Issue by akhlopyk** [FaridSafi/react-native-google-places-autocomplete#509]
Hi there!
Just want to ask if you have an idea how to get street for specified city. I know, there is the way, but I cant figure out what options should I use. Any ideas?

**Comment by VukovicIvan** [comment]
You can do it like this by inputing the longitude and latitude of the city center and then setting the radius.

`query={{
              key: "YOUR_API_KEY",
              language: "en", // language of the results
              location: "44.786600, 20.448900",
              radius: "12000", //12 km
              components: "country:rs",
              strictbounds: true
            }}`

**Comment by akhlopyk** [comment]
@VukovicIvan 
Thanks a lot! You have saved my life!

**Comment by juanlet** [comment]
That works well indeed to restrict the area. Just to add to the solution, if it doesn't get you the right results in ios simulator you need to manually set it going to the simulator top bar menu, **FEATURES -> LOCATION -> Custom Location** and put your actual location(you can search it on google maps or whatever) since the default is **None**(which will make this library not to work at all for ios, you will get **PERMISSION_DENIED** unless you change that.
