### ISSUE TITLE
TouchableHighlight doesn't work when inside Swiper

### ISSUE THREAD

**Issue by arminsalcin** [FaridSafi/react-native-google-places-autocomplete#606]
# Describe the bug

So when u try to use Search input inisde Swiper you can't press on provided address, so in package source i changed TouchableHighlight from react-native to gesture handler everything works. What is solution to this ?

I can change it locally in library and it works, but for future updates..

so 

file GooglePlacesAutocomplete.js
```
import {TouchableHighlight} from 'react-native';
```
Doesnt work but

```
import {TouchableHighlight} from 'react-native-gesture-handler';
```
this works.

**Comment by bell-steven** [comment]
Does [this](https://github.com/FaridSafi/react-native-google-places-autocomplete#use-inside-a-scrollview-or-flatlist) also solve the problem for you? 

The `TouchableHighlight` from `react-native-gesture-handler` is a good solution, but I am wary of adding it as a dependency because it uses native code and would could lead to a more error-prone and cumbersome installation. 

Assuming adding `keyboardShouldPersistTaps ` to the parents views solves your problem, you can still use your own solution by using `patch-package`.

**Comment by arminsalcin** [comment]
Hello ,

Thank you for fast response, i ended up making my own search autocomplete with this [Package](https://github.com/tolu360/react-native-google-places) , thank you for helping im closing issue
