### ISSUE TITLE
currentLocation not working

### ISSUE THREAD

**Issue by uendar** [FaridSafi/react-native-google-places-autocomplete#661]
i get this message :

If you are using React Native v0.60.0+ you must follow these instructions to enable currentLocation: https://git.io/Jf4AR

**Comment by bell-steven** [comment]
Please follow the issue template

**Comment by uendar** [comment]
I have and is not working. Can you help please and do not close the issue!

**Comment by bell-steven** [comment]
The issue template includes the information and context required  to quickly review an issue.  This is open-source software - there is no support or guarantees. 

I copied it all below. 

# Describe the bug

A clear and concise description of what the bug is.

# Reproduction - (required - issue will be closed without this)

Steps to reproduce the behavior - a minimal reproducible code example, link to a [snack](https://snack.expo.io) or a repository.

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  
  ```javascript
    
    
  ```
</details>

_Please remember to remove you google API key from the code you provide here_

# Additional context

- Library Version: [e.g. 1.4.2]
- React Native Version: [e.g. 0.62.2]

- [ ] iOS
- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc
