### ISSUE TITLE
onPress function is not working while i also used keyboardShouldPersistTaps="always" in ScrollView

### ISSUE THREAD

**Issue by Pavaneshpratap** [FaridSafi/react-native-google-places-autocomplete#694]

**Comment by Pavaneshpratap** [comment]
i got my issue..
i was using GoogleplacesAutoComplete in an flatlist component and to resolved issue i just add keyboardShouldPersistTaps="always" in flatlist
thank you

**Comment by consciousweb** [comment]
Thank you for posting this, this was my issue with putting this component inside a ScrollView component

**Comment by sytolk** [comment]
setting `<FlatList keyboardShouldPersistTaps="always"/>` works for me too this must be documented

**Comment by bell-steven** [comment]
@sytolk https://github.com/FaridSafi/react-native-google-places-autocomplete#use-inside-a-scrollview-or-flatlist

**Comment by sigaits** [comment]
After updating to Expo 53, I started having this same issue where a tap on the result row wasn't firing the onPress event. I tried all suggestions, such as the persistTaps option in all ancestors and everything else I came across on the web. Finally, I decided to dig into its code, and in five minutes, I found the culprit. Turns out it's checking for keyboardShouldPersistTaps in its own properties, so it didn't matter if the parent scrollView had it set or not. Once I added that property and set it to 'handled' or 'always', it worked.
