### ISSUE TITLE
Search Bar does not work in a physical device.

### ISSUE THREAD

**Issue by Marcelrama** [FaridSafi/react-native-google-places-autocomplete#90]
Hello!

I am working with Google Places. When I search for my Current Location or any city in a physical device, the Search does not throw me any search result. It only remains loading,  I guess that it might be because of the API key. In my emulator it works fine because I assigned my PC's IP address, Could you please, let me know how do I make it work for "N" number of devices that are in different locations with differents IP?

I attach an apiconsole screenshot.

![captura de pantalla 2017-01-02 a las 2 35 42 p m](https://cloud.githubusercontent.com/assets/22013703/21594612/f0abd4b2-d0fa-11e6-9127-adeea54a271f.png)

Thanks

**Comment by myaskevich** [comment]
Hi
Just disable search restriction by selecting "Any" ("Ninguna") option.

Sincerely,
Maxim Yaskevich




On Mon, Jan 2, 2017 at 9:51 PM +0300, "Marcelrama" <notifications@github.com> wrote:












Hello!


I am working with Google Places. When I search for my Current Location or any city in a physical device, the Search does not throw me any search result. It only remains loading,  I guess that it might be because of the API key. In my emulator it works fine because I assigned my PC's IP address, Could you please, let me know how do I make it work for "N" number of devices that are in different locations with differents IP?


I attach an apiconsole screenshot.





Thanks

**Comment by Marcelrama** [comment]
Hello, thanks for replying, let me try to see if it works
